### ISSUE TITLE
Settings - Columinzer - FileNameMask throws an exception if the regex could not be parsed

### ISSUE THREAD

**Issue by Hirogen** [zarunbal/LogExpert#103]
# Feature
Filenamemask for Columnizers in the Settings:

added a wrong Filename mask => *.log

- LogExpert Version: 1.6.13 / 1.6.14
- Windows Version
- no logfile

- Screenshot
![grafik](https://user-images.githubusercontent.com/8225398/56033953-2442aa80-5d26-11e9-9103-62e94bb7b60f.png)

Following Exception is thrown:
2019-04-12 13:08:46.6182|ERROR|LogExpert.LogTabWindow|RegEx-error while finding columnizer: parsing "*.log" - Quantifier {x,y} following nothing. System.ArgumentException System.ArgumentException: parsing "*.log" - Quantifier {x,y} following nothing.
   at System.Text.RegularExpressions.RegexParser.ScanRegex()
   at System.Text.RegularExpressions.RegexParser.Parse(String re, RegexOptions op)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache)
   at System.Text.RegularExpressions.Regex.IsMatch(String input, String pattern)
   at LogExpert.LogTabWindow.FindColumnizerByFileMask(String fileName)

**Comment by zarunbal** [comment]
I tried to reproduce this error but the error is already handled (it is still written to the log but this shouldn't bring up any popups)
If there is still a error please try to add some more informations

**Comment by Hirogen** [comment]
Yes, there are no popups, just saw it in the logfile

If this is already handled, I'll close the issue
