### ISSUE TITLE
Multiline messages

### ISSUE THREAD

**Issue by j-maly** [zarunbal/LogExpert#11]
Hi, is LogExpert supposed to support multiline messages (like StackTraces) 

My version seems to treat each message of the multiline message as a separate line. E.g. filtering shows only one line of the multiline message.

**Comment by zarunbal** [comment]
Hello @j-maly, with the default Columnizer every line is treated as seperate entry. But if you use a specialized Columnizer / Plugin like Log4J the lines which are one event are keept together. 

If you have a start tag and a end tag on which you can identify one event entry you can use the range search of LogExpert to keep the lines together.

**Comment by j-maly** [comment]
I think the rule is if the line starts with whitespace, it is part of the previous event, e.g. the following should be 2 log events: 

```
17:03 : ERROR : ConsoleApplication1.MyCustomException: some message .... ---> System.Exception: Oh noes!
   at ConsoleApplication1.SomeObject.OtherMethod() in C:\ConsoleApplication1\SomeObject.cs:line 24
   at ConsoleApplication1.SomeObject..ctor() in C:\ConsoleApplication1\SomeObject.cs:line 14
17:04 : INFO : Some other thing... 
```

**Comment by zarunbal** [comment]
I understand the rule but currently as far as I know there is no such Plugin which supports these entries. I flag this Issue as Feature.

**Comment by achimmihca** [comment]
> I think the rule is if the line starts with whitespace, it is part of the previous event

A more general approach would be to create one or more regex rules that define continued lines.
For example, one may log XML formats on a new line:

```
2022-01-01 This is XML:
<config>
    <tool>LogExpert</tool>
</config>
```
Given this example, a rule for continued lines could be "start with whitespace or left angle bracket" `(\s|\<)`

**Comment by achimmihca** [comment]
Another approach could be to consider a line as continued message when if does not fit the columnizer.

**Comment by achimmihca** [comment]
It would be nice if multiline messages are foldable.

For example, a stack traces often span lots of lines. This distracts from the actual error messages.
Especially when the same error (and thus stack trace) occurs multiple times, I do not need to see every single stack trace.

Default for fold/unfold continued lines should be configurable.

**Comment by LevYas** [comment]
Yeah, multiline messages would be great, i.e. 

```
2024-11-21 19:45:53.755 +03:00 [INF] System.Net.Http.HttpClient.Default.LogicalHandler: End processing HTTP request after 51.2452ms - 200
2024-11-21 19:45:53.755 +03:00 [INF] XsmClient.ApiHandling.XsmMetersListRetriever: Response from [https://localhost:1111/API] received in 51ms:
StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Date: Thu, 21 Nov 2024 16:45:53 GMT
  Server: Kestrel
  Transfer-Encoding: chunked
  Content-Type: application/json; charset=utf-8
}

[]
2024-11-21 19:45:53.756 +03:00 [INF] XsmClient.XsmMetersProvider: Requesting batch [200..300], page [1]
```

The rule for matching is that a message continues until the next message is started or EOF is reached.
