### ISSUE TITLE
Idea I'd like to Contribute

### ISSUE THREAD

**Issue by shadowfoxish** [zarunbal/LogExpert#124]
I'm C# developer, so I think I could probably manage this myself, with maybe a little bit of architectural guidance from the project creators/maintainers.

The idea:
Log files I (and my QA peeps) have to deal with frequently include lots of file paths. There is a lot of time spent highlighting, copy and pasting, and other stuff just trying to grab these paths out of the logs to do something with. 

Mockup of the idea: 
![mockup](https://user-images.githubusercontent.com/12143535/62400179-4ae25680-b54c-11e9-84a5-82e7b9e68737.png)

When the feature detects file paths in log text, it would indicate the path somehow (perhaps classic URL underlining, or more modern squiggle underlining). The user can right-click over that portion of the log line and show some  additional context menu items, specific to the file path.

The additional context menu items would include a "Copy Path/URL To Clipboard" command and an "Open With Explorer" command. (shell out to Explorer.exe <the path or file name>)

Detecting file paths isn't difficult, there are really 2 formats, C:\Blah\something.ext or \\server\path\file.ext. More if you want to add URLs/Emails, but I think these things can be configured via RegEx pretty easily. 

I'm wondering, based on this, if this is possible with a plugin, or if it is a direct modification to the application? What other gotchas or advice would you have for someone new to the project?

**Comment by zarunbal** [comment]
Welcome, to the project. 

I have currently a idea to maybe introduce a extension point into the part where the line is retrieved from the current columnizer and then it could be enhanced by plugins (like your idea). 

There is a problem, I'm the next 3 weeks on vacation and not near a PC. I can try to help here after my vacation.

**Comment by shadowfoxish** [comment]
Sounds good, thanks and let me know :)

**Comment by achimmihca** [comment]
This could be useful for opening files from a stack trace as well. Example Java stack trace:

```
Exception in thread "main" java.lang.RuntimeException: A test exception
  at com.stackify.stacktrace.StackTraceExample.methodB(StackTraceExample.java:13)
  at com.stackify.stacktrace.StackTraceExample.methodA(StackTraceExample.java:9)
  at com.stackify.stacktrace.StackTraceExample.main(StackTraceExample.java:5)
```

- The line number is separated by a colon (e.g. `StackTraceExample.java:13` is line 13 in StackTraceExample.java)
- This is not an absolute path. Thus, some base path needs to be configurable
