### ISSUE TITLE
Exception when closing the applicaction: "Index was out of range. Must be non-negative and less than the size of the collection."

### ISSUE THREAD

**Issue by arphox** [zarunbal/LogExpert#169]
# Bug
When closing the application, the following exception occurred:
```
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index


ArgumentOutOfRangeException
   at System.Collections.ArrayList.get_Item(Int32 index)
   at System.Windows.Forms.DataGridViewColumnCollection.get_Item(Int32 index)
   at System.Windows.Forms.DataGridView.FlushDisplayedChanged()
   at System.Windows.Forms.DataGridView.PerformLayoutPrivate(Boolean useRowShortcut, Boolean computeVisibleRows, Boolean invalidInAdjustFillingColumns, Boolean repositionEditingControl)
   at System.Windows.Forms.DataGridView.OnColumnCollectionChanged_PreNotification(CollectionChangeEventArgs ccea)
   at System.Windows.Forms.DataGridViewColumnCollection.Clear()
   at System.Windows.Forms.DataGridView.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at System.Windows.Forms.Control.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at System.Windows.Forms.Control.Dispose(Boolean disposing)
   at System.Windows.Forms.ContainerControl.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at System.Windows.Forms.Control.Dispose(Boolean disposing)
   at System.Windows.Forms.Form.Dispose(Boolean disposing)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

Important questions
- LogExpert Version: 1.8.7
- Windows Version: Windows 10 Pro, Build 1909
- Lokal file or Network: It was a network file
- Used Columnizer: A custom regex columnizer:
`^(?<Level>DEBUG|INFO|WARN|ERROR)\s+(?<Timestamp>[>\d- :,]+\,\d{3})\s+[\d]+ ms\s+[a-zA-Z]+\s+- (?<Message>.*)`
- Is this version specific or a new problem: I don't know, I just started using LogExpert

Optional questions(depends on the problem):
- Continous appending log file?: No
- Size of the file: Around 21 MB
- some specific settings

**Comment by innoreq** [comment]
Problem is still existent, same environment.

**Comment by RandallFlagg** [comment]
@Hirogen this seems to be not relevant in the new version. I suggest closing this issue. If it happens again, we will need new trace anyway.
