### ISSUE TITLE
Loading saved session at startup (double clicking .lxj file) results in crash

### ISSUE THREAD

**Issue by tsimmons** [zarunbal/LogExpert#170]
# Bug
After saving a session, even a simple one with a single file, then exit the application. Double-click the .lxj file (which automatically launches LogExpert) you receive the following error message.

```
Invalid Content: ActiveContent must be one of the visible contents, or null if there is no visible content.

InvalidOperationException
   at WeifenLuo.WinFormsUI.Docking.DockPane.set_ActiveContent(IDockContent value)
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.Activate()
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.SetParent(Control value)
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.SetPane(DockPane pane)
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.SetDockState(Boolean isHidden, DockState visibleState, DockPane oldPane)
   at WeifenLuo.WinFormsUI.Docking.DockPanel.Persistor.LoadFromXml(DockPanel dockPanel, Stream stream, DeserializeDockContent deserializeContent, Boolean closeStream)
   at LogExpert.LogTabWindow.RestoreLayout(String layoutXml)
   at LogExpert.LogTabWindow.LoadProject(String projectFileName, Boolean restoreLayout)
   at LogExpert.LogTabWindow.LogTabWindow_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
If you instead launch LogExpert first and then select File -> Load session... and select the saved session file, it works as expected.

- LogExpert Version: 1.8.7
- Windows Version: Win10 1909 (OS Build 18363.592)
- File loaded from UNC path
- Used Columnizer: LogExpert.TimestampColumnizer
- This worked in 1.5

It is a convenience to be able to save sessions of multiple files to quickly open groups of files with particular columnizer settings and then launch that saved session without *first* having to launch LogExpert and then select File -> Load session...

**Comment by spacemanspiff2007** [comment]
Propably the same as #156

**Comment by tsimmons** [comment]
Ah, I missed that when searching issues. Closed as a duplicate, thanks.
