### ISSUE TITLE
NullReferenceException with filter on regular expression

### ISSUE THREAD

**Issue by jol64** [zarunbal/LogExpert#198]
Important questions
- LogExpert Version - 1.8.7
- Windows Version 10 
- Lokal file or Network - local
- Used Columnizer - none (I think)
- Is this version specific or a new problem - no idea

Optional questions(depends on the problem):
- Continous appending log file? - not relevant
- Size of the file - 1MB suffices
- some specific settings - not that I am aware of
- Screenshot

When I enter "a(" or some other invalid regular expression into the search box, click regular expression and press search, I get a dialog with the following exception:

Object reference not set to an instance of an object.

NullReferenceException
   at LogExpert.Util.TestMatchSub(FilterParams filterParams, String line, String lowerSearchText, String searchText, Regex rex, Boolean exactMatch)
   at LogExpert.Util.TestFilterMatch(FilterParams filterParams, ILogLine line, ILogLineColumnizerCallback columnizerCallback)
   at LogExpert.Util.TestFilterCondition(FilterParams filterParams, ILogLine line, ILogLineColumnizerCallback columnizerCallback)
   at LogExpert.LogWindow.CheckFilterAndHighlight(LogEventArgs e)
   at LogExpert.LogWindow.LogEventWorker()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by Hirogen** [comment]
can you add a screenshot? and the steps you did.

When I enter "a(" into the serach box, with the regular expression option on, I don't get the Exception, maybe I'm doing something wrong!

![image](https://user-images.githubusercontent.com/8225398/141268592-caafa8e4-3997-45b3-8fc8-58154e7d4f56.png)

**Comment by jol64** [comment]
one difference is there for sure. I never use the menu search but always filter 
![image](https://user-images.githubusercontent.com/24666601/141354495-a6264cec-e33d-4158-8a77-1568bea12c78.png)
unfortunately today it crashed just once.

**Comment by Hirogen** [comment]
interesting, trying to reproduce, still nothing, maybe with a bigger logfile, I have to try this on Monday

**Comment by Hirogen** [comment]
does this happen with every logfile or with a specific? I still can't reproduce the bug :(

**Comment by jol64** [comment]
> does this happen with every logfile or with a specific? I still can't reproduce the bug :(

Sorry, that´s a question I cannot answer, I do not have every logfile. I use logviewer on logs of my own software, and report issues that I encounter more than once. And these logs contain personal information, thus I cannot upload one. But I don´t want to be fundamental, that doesn´t get us anywhere. I think the best you could do is catch the exception reasonably and add details like what line you have been parsing, what charcterset might be used, or whatever might be relevant to the code throwing the exception. Then I might be able to extract some lines of the log file that triggers the exception  (unless it is probabilistic rather than deterministic).
Thanks, Joachim

**Comment by Hirogen** [comment]
> Sorry, that´s a question I cannot answer, I do not have every logfile. I use logviewer on logs of my own software, and report issues that I encounter more than once. And these logs contain personal information, thus I cannot upload one. 

sorry you missunderstood, i don't want your logfiles, just being interested if this happens with every logfile, you use regexes in the filter dialog, or if this happens only in specific cases and specific logfiles.

Since I can not reproduce the error and the code at this position looks fine, I try to narrow it down, to how I might be able to reproduce the error with one of my own logfiles

**Comment by jol64** [comment]
Cannot answer that question either, because what I do with Logviewer depends on what the customer reports as an issue, and then I start filtering on the logs. Though I cannot tell it happens with every log file I use, but frequently.

I´d definitely suggest wrapping the exception and enrich it with more information. That is an approach you definitely can write a test for by throwing a null pointer exception at random in tests.

**Comment by Hirogen** [comment]
> I´d definitely suggest wrapping the exception and enrich it with more information. That is an approach you definitely can write a test for by throwing a null pointer exception at random in tests.
Actually there should be a line where this happens, at least with the test exceptions, there are always lines where this happened:
As you can see here:
![image](https://user-images.githubusercontent.com/8225398/175096097-aa6dcf7b-10e3-43bc-a74f-ac5a14f986dc.png)

Maybe you could post the another screenshot again with the exception or you can extract the exception from the logexpert.log that is stored in at "%AppData%\Roaming\LogExpert\logs"

**Comment by RandallFlagg** [comment]
@Hirogen is thi issue solved? If yes can it be closed? Is it related to issue #232?

**Comment by Hirogen** [comment]
I close this issue, testing with the version 1.11.0 did not show a exception while filtering with regexes
