### ISSUE TITLE
CsvColumnizer: An unhandled error has occured.

### ISSUE THREAD

**Issue by Akaizoku** [zarunbal/LogExpert#199]
# Bug

Error occured after modifying the default CSV columnizer to use commas (`,`) instead of semi-colons (`;`) as a separator. It does not happen if I revert the change and apply it again.

> An unhandled error has occured. Please report to the developer.

```java
InvalidArgument=Value of '0' is not valid for 'SelectedIndex'.
Parameter name: SelectedIndex


ArgumentOutOfRangeException
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at LogExpert.LogWindow.SetColumnizerInternal(ILogLineColumnizer columnizer)
   at LogExpert.LogTabWindow.selectFilterToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

[logexpert.log](https://github.com/zarunbal/LogExpert/files/7083379/logexpert.log)

# Environment

- LogExpert Version: 1.8.7
- Windows Version: Microsoft Windows Server 2019 Datacenter Version 10.0.17763 Build 17763
- Local file or Network: Local
- Used Columnizer: CsvColumnizer.CsvColumnizer
- Is this version specific or a new problem: N/A

**Comment by maddin30** [comment]
i could reproduce it.
the problem occurs if you have 2 files open (see attachments). one with semicolon the other with comma as seperator.

if you then change the seperator character in the csv columnizer settings you will get the mentioned error.


[semicolon.csv](https://github.com/zarunbal/LogExpert/files/7558474/semicolon.csv)
[comma.csv](https://github.com/zarunbal/LogExpert/files/7558475/comma.csv)
.

**Comment by maddin30** [comment]
here the steps with screenshots... 

changed from ";" to "," 
![grafik](https://user-images.githubusercontent.com/35540855/142294637-eeb8b02c-c404-40b0-b2a1-e713395902ab.png)

press ok, and you get the nice window.

![grafik](https://user-images.githubusercontent.com/35540855/142294751-1199a714-7385-4296-b4ae-fbc9bde3eadf.png)

**Comment by Hirogen** [comment]
I can reproduce this error, will fix soon

**Comment by Hirogen** [comment]
this problem seems to be only with csv, because you can have different delimiter chars for different files.

This happens if the currently selected file has a different delimiter char as the "selected" one in the config field.

the current selected line of the active "tab-window" is used for checking the validity of the csv. The problem seems to be that multiple csv files don't have there own columnizers, but rather use the same.

Not sure yet, how to fix this problem.
