### ISSUE TITLE
LogExpert Crashes with Unhandled Error Message

### ISSUE THREAD

**Issue by skcruzer** [zarunbal/LogExpert#267]
# Bug
I just started using LogExpert for the first time for work. I am having issues with the application crashing on me frequently and this pop-up:

> An unhandled error has occured. Please report to the developer.
```
Invoke or BeginInvoke cannot be called on a control until the window handle has been created.

InvalidOperationException
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.BeginInvoke(Delegate method, Object[] args)
   at LogExpert.LogWindow.logFileReader_LoadFile(Object sender, LoadFileEventArgs e)
   at LogExpert.LogfileReader.ReadToBufferList(ILogFileInfo logFileInfo, Int64 filePos, Int32 startLine)
   at LogExpert.LogfileReader.FireChangeEvent()
   at LogExpert.LogfileReader.FileChanged()
   at LogExpert.LogfileReader.MonitorThreadProc()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

# Version
- LogExpert Version 1.5 / 5493
- Windows 10 Enterprise Version 20H2

# Notes
- If I re-load a few times, it works for a bit. I still get that error above from time to time
- I already have loaded sessions that a colleague shared with me

**Comment by Hirogen** [comment]
Since your are using Windows10 20H2 could you please try it with the current version 1.9.0?
