### ISSUE TITLE
getting error message 

### ISSUE THREAD

**Issue by yoramo1** [zarunbal/LogExpert#32]
this message was posted on another issue related to memory leak 'zarunbal' asked to opend a new issue for this one. here it is:

I'm getting this message all the time

Value of '45000' is not valid for 'Value'. 'Value' should be between 'minimum' and 'maximum'.
Parameter name: Value

ArgumentOutOfRangeException
at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
at LogExpert.LogWindow.OnProgressBarUpdate(ProgressEventArgs e)
at LogExpert.LogWindow.EnterLoadFileStatus()
at LogExpert.LogWindow.LoadFile(String fileName, EncodingOptions encodingOptions)
at LogExpert.LogWindow.ReloadNewFile()
at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

**Comment by zarunbal** [comment]
@yoramo1 thanks for moving your message. I'll cleanup the other issue.

**Comment by zarunbal** [comment]
Fixed with this release. If it still persists please reopen the bug
