### ISSUE TITLE
Drag and drop file crashes the program

### ISSUE THREAD

**Issue by SpaceOgre** [zarunbal/LogExpert#4]
Version: 151
OS: Windows 10

When I drop files into the program from explorer it crashes. If I open the same file from with in the program it works fine.

Could not find a log file to give you.

**Comment by zarunbal** [comment]
@SpaceOgre If the Popup from Windows was displayed that the application had an unexpected error the exception should be visible in the EventViewer from Windows (eventvwr.exe -> Windows Logs -> Application, and there the Application Error entry **and** the .NET Runtime exception)

**Comment by SpaceOgre** [comment]
Application Error:
```
Faulting application name: LogExpert.exe, version: 1.5.0.0, time stamp: 0x59e92028
Faulting module name: msvcrt.dll, version: 7.0.15063.0, time stamp: 0x3280d1b7
Exception code: 0xc0000005
Fault offset: 0x0000000000073680
Faulting process id: 0x2d24
Faulting application start time: 0x01d34d7062663cbe
Faulting application path: C:\Users\DanielNordström\Downloads\v151\LogExpert.exe
Faulting module path: C:\WINDOWS\System32\msvcrt.dll
Report Id: 34db33ca-f641-42f8-a350-8b66f11888f3
Faulting package full name: 
Faulting package-relative application ID: 
```

.Net Error
```
Application: LogExpert.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at System.Windows.Forms.UnsafeNativeMethods.CallWindowProc(IntPtr, IntPtr, Int32, IntPtr, IntPtr)
   at System.Windows.Forms.NativeWindow.DefWndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.ComboBox.DefChildWndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.ComboBox.ChildWndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)
```

**Comment by zarunbal** [comment]
@SpaceOgre Thanks for the infos. I can reproduce the problem.

I have found a workaround, until I can fix the root of the problem (which will take some time). Could you please test the workaround if this works for you?

Create a start.cmd (you can name it differently) in the folder where the LogExpert executable is located with the content below. After you saved this start LogExpert with this CMD file.
```
set __COMPAT_LAYER=DisableUserCallbackException
echo %cd%
start "" logexpert.exe
exit
```

Some more information under:
https://stackoverflow.com/questions/5600735/how-do-i-fix-win7-app-compatibility-shim-with-disableusercallbackexception
https://blogs.msdn.microsoft.com/cjacks/2011/11/22/managing-the-windows-7-program-compatibility-assistant-pca/

**Comment by SpaceOgre** [comment]
@zarunbal Hi, the workaround works for me too 👍

**Comment by zorglups** [comment]
Thanks for the work-around. I had user almost ready to stop your wonderful tool because of that crash :-(

Looking forward to get the correction 👍 

Keep up the good work!

**Comment by zorglups** [comment]
@zarunbal,

Really sorry to bother you with this as it is probably not at the top of your list (since you proposed a work-around).
Actually, I'm trying to convince many people to use it but the fact that they cannot launch the exe but instead have to launch the bat refrain them.
Do you think you could look to it to bring a solution?

Thank you for your work.

Pierre

**Comment by zarunbal** [comment]
New release is finaly out there. For me the Drag'n'Drop crash is fixed. Please test the new release if it works for you too and give some feedback. Thanks to louisledev for his fix.

**Comment by zorglups** [comment]
GREAT !!! THANK YOU !!!


2018-01-29 22:31 GMT+01:00 zarunbal <notifications@github.com>:

**Comment by nathanrobb** [comment]
1.6.6 drag drop crashed log expert
Come here 🙏 for a resolution.
See 1.6.7 🎉 

Thanks guys.
