### ISSUE TITLE
Random app crash

### ISSUE THREAD

**Issue by Pr0metheus2** [zarunbal/LogExpert#62]
Hi,

randomly (couple of times per day), I am getting following error message with app crashes. Nine files opened, two of them with "Filter to tab".

![image](https://user-images.githubusercontent.com/9161285/40054267-8d635470-5844-11e8-9cf0-8700ec27c60c.png)

**Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

ArgumentOutOfRangeException
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Windows.Forms.DataGridViewRowCollection.get_Item(Int32 index)
   at System.Windows.Forms.DataGridView.get_SelectedRows()
   at LogExpert.LogWindow.selectionChangedTrigger_Signal(Object sender, EventArgs e)
   at LogExpert.DelayedTrigger.OnSignal()
   at LogExpert.DelayedTrigger.worker()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()**

# Bug

Important questions
- LogExpert Version - 1.10.13
- Windows Version - 7 Pro x64
- Lokal file or Network - Network files
- Used Columnizer - No

Optional questions(depends on the problem):
- Continous appending log file? - yes
- Size of the file - Up to 12MB each
- some specific settings - No

**Comment by zarunbal** [comment]
is this error specific to the version 1.6.13?

**Comment by Pr0metheus2** [comment]
Yes, I think so.

**Comment by Pr0metheus2** [comment]
Will test the latest release.

**Comment by Hirogen** [comment]
@Pr0metheus2 could you test this with version 1.6.14 and confirmed that it has been fixed?

**Comment by zarunbal** [comment]
I assume that this bug is resolved. If it still there feel free to reopen this bug
