### ISSUE TITLE
Highlighter - Regex highlight- ArgumentException - if the regex is wrong logexpert shutsdown

### ISSUE THREAD

**Issue by Hirogen** [zarunbal/LogExpert#69]
Reproducable Bug with the Highlighter.

If a wrong regex has been added, the highlighter cannot parse it and logexpert crashes repeatedly.

Current Workaround, don't close the error-dialog and remove the hightlighter by directly editing it.

Possible Soluation:
Check the regex when the apply button is pressed and if the regex is wrong, don't apply it and show the user the error message
![highlighter](https://user-images.githubusercontent.com/8225398/42442072-029eded0-836a-11e8-8851-145a9680f774.png)

Configuration as follows:
- LogExpert Version: 1.6.13
- Windows Version: Version 6.1 (Build 7601: Service Pack 1)
- Lokal file or Network: File or Network does not matter
- Used Columnizer: standard
- All Versions

Optional questions(depends on the problem):
- Continous appending log file? Continous and no continous logfile, does not matter
- Size of the file: does not matter, all sizes

regex used
ACDState = \[State = Off)(.+)\]

# Feature in use
Highlighter

Exception from Dialog:
parsing "ACDState = \[State = Off)(.+)\]" - Too many )'s.

ArgumentException
   at System.Text.RegularExpressions.RegexParser.ScanRegex()
   at System.Text.RegularExpressions.RegexParser.Parse(String re, RegexOptions op)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options)
   at LogExpert.HilightEntry.get_Regex()
   at LogExpert.LogWindow.CheckHighlightEntryMatch(HilightEntry entry, ITextValue column)
   at LogExpert.LogWindow.FindMatchingHilightEntries(ITextValue line)
   at LogExpert.LogWindow.CheckFilterAndHighlight(LogEventArgs e)
   at LogExpert.LogWindow.LogEventWorker()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by Hirogen** [comment]
has been fixed
